---
# output:
#   html_document: 
#     css: "style2.css"
#   word_document: default

output:
  prettydoc::html_pretty:
    theme: architect
    toc: yes
    toc_depth: '3'
    number_sections: false
    self_contained: false  

title: "百炼为战五星人物动态"
author: "公理天城翻译官"
date: "更新时间：`r Sys.Date()`"
---


目前游戏最高星等为五星，虽然六星听了很久，连T5C火种也因为卡邦的疏忽被玩家买到过，但卡邦貌似已经没有资源来投入做六星的体系，所以五星也许是游戏最终的形态了。

以下列出五星人物的获取方式演变历程，定期更新。

*注：2020年人物逐渐稳定之后，卡邦已经把所有机器人都更新到2\~4星的池子中，新人物如挽歌也已经进入了2\~4星池，相信后续也会逐步更新，保证五星机器人都能解锁100锻。*

# 五星普通池
一般指五星碎片水晶能开到的机器人。3\~5星水晶和5星专属水晶中除了该水晶专属人物，其他5星也在5星普通池中选人。

## 第一波（2018年4月，6.0版）

- 碾碎器，猩猩队长
- 阿尔茜，漂移
- 警车，路障
- 犀牛，震荡波
- 爆威，黄蜂勇士
- 红蜘蛛，通天晓

## 第二波（2018年8月，7.0版）

- 钢锁，斗擎
- 热破，碎骨魔
- 反冲，黄豹
- 幻影，声波
- 惊破天，搅拌者
- 战威，恐龙勇士

## 第三波（2019年6月20日）

- 汽车大师
- 雷震
- 爵士

## 第“四”波

自从发布第三波后，由于新人物基本上出到了头，为了拖延，卡邦不再这么豪迈地扩充五星普通池，而是变成了每月加一人。在加人的同时发布此人物的专属水晶（限时用12500五星碎片换一个，对该专属人物的掉落率大约15%）

- 铁皮（2019年8月16日）
- 录音机（2019年9月13日）
- 战擎（2019年10月18日）
- 天火（2019年11月14日）
- 风刃（2019年12月12日）
- 千斤顶（2020年1月16日）
- 横炮（2020年2月14日）
- 探长（2020年3月15日）
- 救护车（2020年4月16日）
- 野牛（2020年5月17日）
- 蝎子（2020年6月11日）
- 喷气机（2020年7月16日）
- 狂飙（2020年8月15日）

在狂飙加入之后，普通五星池已经有40个机器人，剩下的6个（震天尊，亡灵天尊，大黄蜂，小黄蜂，惊天雷，黑擎）只能在泰坦货币商店买到，如无意外，普通五星池不会再改变了。

## 普通池后续人物

- 挽歌（在2022年3月31日，G1铁皮发布时，已有玩家从普通5星水晶中开出挽歌）
- 闹翻天（2022年6月底）


# 通用币人物
天火的发布**暂时**宣告了新人物开发的停止（但是后面还出了很多新人物），每月的专属机器人币也变成了通用币，通用币人物每月在商店中上架3\~4个，轮完之后循环，所以只要你慢慢攒，总能拿到自己要的普通池机器人。


## 2019年

- 1月：汽车大师，雷震，爵士
- 2月：铁皮，录音机，风刃
- 3月：喷气机，救护车
- 4月：战擎，反冲
- 5月：探长，震荡波，搅拌者
- 6月：野牛，恐龙勇士，路障
- 7月：天火，黄豹，战威
- 8月：横炮（平衡性调整），阿尔茜，黄蜂勇士
- 9月：狂飙，幻影（平衡性调整），警车
- 10月：爆威，热破，碾碎器（平衡性调整）
- 11月：通天晓（平衡性调整），猩猩队长，巨蝎勇士
- 12月：斗擎，犀牛，碎骨魔

## 2020年

- 1月：救护车，红蜘蛛，爵士
- 2月：雷震，声波，喷气机
- 3月：铁皮，录音机，风刃，汽车大师
- 4月：千斤顶，路障，恐龙勇士
- 5月：探长（平衡性调整），反冲（平衡性调整），震荡波
- 6月：战擎，搅拌者，漂移，野牛
- 7月：黄蜂勇士、战威、警车
- 8月：钢锁（平衡性调整），幻影，黄豹。此外声波得到平衡性调整。
- 9月：横炮，阿尔茜，天火，狂飙
- 10月：通天晓，猩猩队长，碎骨魔
- 11月：热破，斗擎，惊破天
- 12月：犀牛，巨蝎勇士，爆威，碾碎器

总结：2020年每个季度都采用了3+3+4的方式发布10个人物，一年40个，也正好对应40个普通五星池的人物。~~游戏已经基本上趋于圆寂的状态~~。


## 2021年

2021年的人物币人物出场顺序至5月都**与2020年如出一辙**，卡邦貌似已经完全固化了这个顺序。如果游戏一直存在下去，这也算一种能让新玩家入坑后明确规划自己发展方向的途径。

2021年，没有出六星，而是出了**五星六阶**的升级方式：需要一种新的火种——T5B。T5B的获取在最初略显困难，很多玩家为了抢第一杯羹，不惜大量出售T4B来换取。但自从加入到特殊探索任务的奖励（2000精华）后，最佛系的玩家两个半月也能搞到一个。加上T3A从腐朽要塞水晶中可以大量获得，升级六阶的压力依然在T4C上。

今年周年庆新出了爆破系的飞过山。

就在大家以为游戏慢慢凉了的时候，挽歌在12月22日登场。

## 2022年

22年开始，随着卡邦高调公布新的发展计划，游戏慢慢开始有了起色，而月度的人物币人物也不再遵循之前的规律，二月之后也不再称为月度机器人而是**展示机器人**，所以后面改为按发布日期列出。

- 1月：救护车，爵士，红蜘蛛
- 2月：声波，雷震，喷气机
- 2月24日：横炮，警车，巨蝎勇士，惊破天
- 3月31日：狂飙，录音机，恐龙勇士，碾碎器
- 5月5日：碎骨魔，热破
- 5月19日：猩猩队长，黄豹，野牛，反冲
- 6月23日：挽歌，阿尔茜，千斤顶，震荡波



2月4日的时候，游戏公司又宣布了新的人物闹翻天和G1铁皮。新的启动画面上又出现了一名疑似是补天士的角色。

闹翻天在2月25日登场。

G1铁皮在3月31日登场。

4月12日YouTube的Hasbro Pulse直播中公布了补天士，这张图上依然有一个模糊的影子，网友猜测是BW霸王龙，也有猜是飞毛腿和双面人（出击/反击）的。

5月4日9.1.0更新新封面，不但补天士登场，滑流（Slipstream，一译璇流）也出现了！

滑流在5月19日登场。

补天士在6月23日登场。同时预告的有**音板（Soundblaster），克劳莉娅（Chromia），飞毛腿（Sunstreaker）和封锁（Dead End）**——看来卡邦真的是在新人物方面加大了研发投入！

# 世代币人物
指2019年9月卡邦针对G1人物举行的活动，每周世代币商店都有一批人物上架：


- 第1周：战擎/震荡波/阿尔茜/惊破天/汽车大师/爵士
- 第2周：天火/战威/横炮/幻影/狂飙/钢锁
- 第3周：声波/警车/雷震/录音机/通天晓/喷气机
- 第4周：千斤顶/风刃/红蜘蛛/救护车/野牛/反冲

# 野兽币人物

指2019年12月卡邦针对BW人物举行的活动。总共就6个BW人物（猩猩队长/巨蝎勇士/黄豹/犀牛/黄蜂勇士/恐龙勇士），尽数上架。

# 冷饭活动

2022年开始为填补新人物发布间空档期（两周），卡邦会把一些之前的活动重新拿出来。例如霸天虎活动，电影人物活动。套路都是肝主题币，换3/4/5星人物。

# 泰坦碎片（巨人碎片）商店人物
以下人物在泰坦碎片商店可以购得，长期有效。

|    人物    	|  价格  	|
|:----------:	|:------:	|
| 饿鲨S-1000 	| 130000 	|
| 战术大黄蜂 	| 130000 	|
| 侦查大黄蜂 	| 170000 	|
|   惊天雷   	| 170000 	|
| 暗黑擎天柱 	| 200000 	|
|   震天尊   	| 240000 	|
|  亡灵天尊  	| 240000 	|
|  飞过山   	| 200000 	|


# 独家人物
除此之外，下列人物的五星版本有独特的方式获取：

- 战术大黄蜂：金轮水晶
- 侦查大黄蜂：金轮水晶。以及在当时的世代活动中，完成所有世代月目标免费赠送
- 惊天雷：暴雨天水晶，惊天雷5星竞技场
- 暗黑擎天柱：黑暗矩阵水晶（3~5星）
- 震天尊：更好的能量水晶
- 饿鲨S-1000：5星饿鲨水晶小概率开出
- 挽歌：在发布时直接明码标价购买：￥648一个五星，没有盲盒套路
- 闹翻天：直接氪金648或者通过限时礼包（3500能量块）购买，比较亲民，后续可通过精英传送水晶（3~5星）开出来，可以直接能量块购买，有一周的传送事件竞技场可以获得碎片
- G1铁皮：同闹翻天的营销策略完全相同。648￥直接买-开精英要塞水晶-能量块礼包-专题竞技场开水晶，分阶段满足各类玩家的需求。
- 滑流：精英恶毒嘲讽水晶，其他没变。从这里也能看出卡邦正在试点“五周专题人物+两周炒冷饭”的人物发布策略。
- 补天士：精英英勇火焰水晶。


<!-- ```{r echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- library(magick) -->
<!-- # Produce graphic -->
<!-- fig <- image_graph(width = 800, height = 600, res = 96) -->
<!-- ggplot2::qplot(factor(cyl), data = mtcars, fill = factor(gear)) -->
<!-- invisible(dev.off()) -->


<!-- frink <- image_read("https://jeroen.github.io/images/frink.png") -->

<!-- fig %>% -->
<!--   image_rotate(10) %>% -->
<!--   image_implode(.6) %>% -->
<!--   image_composite(frink, offset = "+140+70") %>% -->
<!--   image_annotate("Very usefull stuff", size = 40, location = "+300+100", color = "navy", boxcolor = "pink") -->
<!-- ``` -->


