---
output:
  html_document: 
    toc: yes
    toc_depth: '3'
    df_print: paged
    css: "style2.css"
    # theme: cerulean
  prettydoc::html_pretty:
    theme: hpstr
    toc: yes
    toc_depth: '3'
    number_sections: true
    self_contained: false
title: "塞伯坦之魂"
---

# 上篇

塞伯坦联盟群的格局，是和别处不同的：都是一群百炼玩家，一群胶佬，一群政客，可以随时吹水/撕逼/开车。国服的玩家，打完了盟战和特任，每每花几百能量块，买一些高等机器人水晶，测测欧气，——这是开服头一年的事，现在每个3~5星水晶要200能量块，——开着公共频道，吹吹自己开到的新角色，再跟以**羽炫大神**[^羽炫]领衔的“**阁**字盟”[^阁]的朋友讨论一下生物、历史、地理；倘肯多花几千能量块，便可以买几个独家模块水晶，或者T4B礼包，做吹牛的谈资了，如果拿出遗迹券，那就能买遗迹，然后卖了换黄金，但这些玩家，多是收藏党，大抵没有这样阔绰。只有开服玩到现在的土豪，才大大咧咧买进黄金探长遗迹，然后把它卖了。

我从离开某个老外盟起，便在“大家庭”群里当伙计，群主[^马团团]说，战力太低，怕侍候不了开服土豪，就在外面做点事罢。外面的散户盟友，虽然容易说话，但唠唠叨叨缠夹不清的也很不少。他们往往要亲眼看到论坛**下月机器人**的截图，看过游戏里收到邮件没有，又亲看人物币商店里面这几个机器人上架，然后放心：在这严重监督下，编谣言说下个月是钢锁漂移也很为难[^下月机器人]。所以过了几天，群主又说我干不了这事。幸亏念总[^念总]的情面大，辞退不得，便改为专管写全人物教程[^人物教程]的一种无聊职务了。

[^羽炫]: 指贴吧用户“羽炫2013”。2020年疫情居家期间加入的某传奇人物，号称有战力9万的基地，25个55满锻，并且在游戏的“内测服”玩着6星机器人，全服排名前十的盟他都呆过，等等。只在贴吧活跃，从未透露过自己游戏账号。
[^阁]: 指疫情期间公屏中出现的一大票新盟，都带“阁”字，大有取代塞伯坦联盟的趋势。然而随着中小学复课，已逐渐消失。
[^下月机器人]: 曾经大家都比较关注下月机器人，一到月半就开始问下月出什么机器人，卡邦的版主也总留下一些“猜谜”与玩家互动。但自从卡邦总部“搬到”印度，基本上游戏已经被放弃，玩家也多有弃坑，问的人自然少了。由于很长时间钢锁和漂移都没有加入人物币商店，于是每月有人问的时候，总有人编说下月有钢锁或者漂移……
[^马团团]: 指玩家“马团团”，塞伯坦联盟大家庭现任群主。再注：一碰到有人开车，群主的职务就会被人“客气”地交来交去，但终归会回到团团手里。
[^念总]: 指玩家“念欣郎”，塞伯坦联盟创始人。
[^人物教程]: [《百炼为战全人物解析》](./chars_book/index.html)

我从此便整天的泡在HTML和Markdown代码里，专管我的职务。虽然没有什么失职，但总觉得有些单调，有些无聊。群主是一副凶脸孔，盟友和胶佬也没有好声气，一言不合就撕逼，或者上历史/政治课，或者晒玩具，教人活泼不得；只有**龙欣在群里发个“？”号**[^问号]，才可以把讨论带到正轨，所以至今还记得。

[^问号]: 龙欣经常以为群里的讨论跟他有关，又不确定，于是发个“？”号来试探。


龙欣是半路入坑却**卖过黄金探长遗迹**的唯一的人[^金头探长]。他身材很高大；青白脸色，皱纹间时常夹些伤痕；一副**忧国忧民的样子**[^汉少平等]。虽然用的是60级的账号，可是队伍配置看不出什么章法，似乎不知道锻造，也没听说过协同。他对人说话，总是满口**黑绿黄红蓝**[^黑绿黄红蓝]，教人半懂不懂的。因为他姓龙，欣赏**声波**[^声波]，又不会用，别人便借寓言故事“叶公好龙”替他取下一个绰号，叫作龙欣。龙欣一到店，所有正在肝竞技场的人便都看着他笑，有的叫道，“龙欣，你又在一厅就吃完15个药了！”他不回答，对柜里说，“来一个高等模块水晶。”便排出75能量块。他们又故意的高声嚷道，“你一定又偷开盟友水晶了！”龙欣睁大眼睛说，“你怎么这样凭空污人清白……”“什么清白？我前天亲眼见你登录了阿兰[^阿兰]的账号偷开水晶，后来被狼牙棒暴菊了。”龙欣便涨红了脸，额上的青筋条条绽出，争辩道，“测欧气不能算偷……测欧气！……铁杆盟友之间的事，能算偷么？”接连便是难懂的话，什么“**黑绿亡国**”，什么“**五胡乱华**”之类，引得众人都哄笑起来：群内外充满了快活的空气。

[^金头探长]: “金头探长好用吗？——我把它卖了！”
[^汉少平等]: “希望有生之年看到汉少平等，内安外硬，江山统一！”
[^黑绿黄红蓝]: 黑绿指黑人和绿教问题，黄是指开车（一说指龙欣某一段时间对自己是黄种人的不认同，他认为白种人才高贵，并且认为汉族有可能被称为白种人），红是红刺（《绝迹重生》中的复制型杂兵），龙欣很长时间用的头像（并且一直盼着百炼为战出红刺），蓝是指~~他一直抽不到科技T4C~~他钟爱声波（经提醒，他说的科技T4C是青色的）。
[^声波]: 龙欣经常在群里说“声波觉醒100好不好哇？”然而从来不付诸实践。
[^阿兰]: 指玩家“AlannL”，塞伯坦之刃大神之一，据说最多时一人打之刃一半的号。

听人家背地里谈论，龙欣原来也认真玩过游戏，但终于没有钻研进去，又不会氪金；于是愈玩愈烂，弄到将要找人代打了。幸而几乎各个群都有加[^加群]，便在各个群里带带节奏，博网友的谈资，私加几个操作高手帮他代打大师[^代打大师]。可惜他又有一样坏毛病，便是进盟战就犯悚。**一碰到路障就非要击倒他**，然后被规避，被施加逆火后放S技自杀，再到群里抱怨，大家教过之后又忘。如是几次，跟他一边的盟友干脆不等他直接吃电池抢怪了。龙欣没有法，每到周四下午，就在群里说“**今晚大伙先打，我007去了**”[^007]。盟战开始后的23小时59分内，便连人和账号，一齐失踪，连走公共步数都省了。但他在权健盟里，品行却比别人都好，就是只进图，不打怪；虽然间或没有进图，但不出23小时59分，定然进图，始终三人满血0分过图拿奖励[^奖励]。

[^加群]: 在塞伯坦联盟各主要群、天尊圣约、权健等知名讨论群都有龙欣的身影和教诲。
[^代打大师]: 龙欣基本上不会自己打大师（主要也是**打不过铁皮**），很多绝世高手为了给他代打都不惜把自己主号卖掉。
[^007]: 自从龙欣开始叫嚷着要辞工，一直都说为了补上前面一个人的工作，他要按007的节奏加班，所以没时间打盟战，不过各个群里他都依然时时刻刻盯着，有跟黑绿、治国、开车相关的话题他都第一时间出现。
[^奖励]: 蹭奖励的最基本条件就是要进图。


龙欣开出一个三星修复模块，涨红的脸色渐渐复了原，旁人便又问道，“龙欣，你当真打过盟战么？”龙欣看着问他的人，显出不屑置辩的神气。他们便接着说道，“你怎的连一个小boss也抢不到呢？”龙欣立刻显出颓唐不安模样，脸上笼上了一层灰色，嘴里说些话；这回可是全是**冉闵**[^冉闵]、**党国**[^党国]、**马红**[^马红]之类，一些不懂了。在这时候，众人也都哄笑起来：店内外充满了快活的空气。

[^冉闵]: 龙欣的民粹精神想必来自于「武悼天王冉闵，屠胡数百万，拯救汉民族」这一桩伪造夸大史料所致的网络神话。
[^党国]: 龙欣信奉GMD，经常在群里问微信表情中是否打出4V的旗帜，后来往往以澳大利亚旗代替。
[^马红]: “我信汉，其次民红，还是汉好”；“现在的马红，比民红还党国”

在这些时候，我可以附和着笑，群主是决不责备的。而且群主见了龙欣，也每每这样问他，引人发笑。龙欣自己知道不能和他们谈天，便只好向孩子说话。有一回对我说道，“你满锻过五星机器人么？”我略略点一点头。他说，“满锻过，……我便考你一考。四星招牌升级程序，给谁用最好？”我想，一厅都打不完的人，也配考我么？便回过脸去，不再理会。龙欣等了许久，很恳切的说道，“不知道罢？……我教给你，记着！这些知识应该记着。将来做群主的时候，吹牛逼要用。”我暗想我们群主一人代打十几个号，离退休还很远呢，而且我们群主也从来都是闭着眼睛喂招牌，回回道具使用排第一；又好笑，又不耐烦，懒懒的答他道，“谁要你教，不就是给饿鲨吃最多经验么？”龙欣显出极高兴的样子，将两个指头的长指甲敲着柜台，点头说，“对呀对呀！……**小钢索[^小钢索]追过四个女生**，你知道么？”我愈不耐烦了，努着嘴走远。龙欣刚翻出之刃的聊天记录，见我毫不热心，便又叹一口气，显出极惋惜的样子。

[^小钢索]: 指玩家“钢索的酒吧”，塞伯坦联盟另一位传奇人物。成名于澳大利亚的留学生高手，最大的遗憾是至今依然单身，并引以为荣。网友们替他着急，编出过很多**他追到不同女生的野史**（这句话本身也是野史）。


有几回，阁字盟的盟友听说了龙欣的伟大，也赶热闹，在公屏围住了龙欣。他便给他们讲汉族的民粹精髓，一人一个故事。孩子们听完，仍然不散，在公屏中说自己要把这些讲给学校老师听。龙欣着了慌，手写输入法划拉不利索，“你们门怎么可以这样，回去打门战[^盟战]去。”又补充说，“门战门战！多门对战也。”于是这一群孩子都在笑声里走散了。

[^盟战]: 刚开始的时候大家以为龙欣是有点口音，meng/men不分，后来据他自己说是“盟”字不会写，用“门”代替，这个说法很靠谱，因为他玩的是英文版，可能没见过“同盟”这个译法。至于说在微信群天天看其他人打“盟战”二字为什么没有学会……


龙欣是这样的使人快活，可是没有他，盟战还是照常进行。

有一天，大约是8.4.3更新后两三天，群主正在开车，翻了下聊天记录，忽然说，“龙欣长久没进盟战了。不是一直说**辞工**[^辞工]好好打游戏的呢！”我才也觉得他的确长久没出现了。一个正在开**整流水晶**[^整流水晶]的人说道，“他怎么会来？……他被毁号了。”群主说，“怎么讲？他不是在之刃混得不错吗”“他总仍旧是盟战划水[^划水]，0分过全图。早就被苍老师[^刃大大]踢出去了。这一回，是自己发昏，竟跑到之光去划水了。之光的二哥[^二哥]的脾气，是惹得的么？”“后来怎么样？”“怎么样？先交出账号密码，后来是把四星喂完，再把火种卖光。”“后来呢？”“后来把水晶开完，能量块都开高等模块用完了。”“还有么？”“最后把所有遗迹都卖了！这就可以弃坑了吧。”群主也不再问，仍然慢慢的在群里开车。

[^划水]: 龙欣总是可以在盟战的时候找到各种理由不打，然而在群里却说“打门战，就是要18人同心协力，一起打，哪有靠3\~5个人打，其他人混的？”
[^辞工]: 龙欣一直说干活干得不开心，公司关系户太多，要辞工，但基本上不见行动。网友纷纷怀疑他才是老板。
[^整流水晶]: 很多玩家在前一个盟战地图中攒下的古代圣所水晶碎片让卡邦颇为惦记，于是弄了一个“整流水晶”来诱骗/逼迫玩家把古代圣所水晶碎片换掉，如果不按时转换为整流水晶，则最终会被转换为黄金废掉。
[^刃大大]: 指玩家“风间流苍月”。塞伯坦之刃盟主。
[^二哥]: 指玩家“颖州温二爷”。塞伯坦之光前盟主，人妻杀手。


更新之后，百炼是是一天比一天卡，8G运存以下的手机差不多都玩不了了；苹果版的闪退十分严重，国服的玩家都只好挂着VPN打游戏；我的小米8，也快要退役了。一天的下半天，国服没有一个人在公屏，我正合了眼坐着。忽然间听得一个声音，“来一个高等模块水晶。”这声音虽然极低，却很耳熟。看时又全没有人。站起来向外一望，那龙欣便拿着一台iPhone 6对了门槛坐着[^4.7]。他脸上黑而且瘦，已经不成样子；账号里面105能量块，外加一个半整流水晶和两个精英四小时水晶；见了我，又说道，“来一个高等模块水晶。”群主也伸出头去，一面说，“龙欣么？你还欠十九点盟战体力呢！”龙欣很颓唐的仰面答道，“官对[^官对]……今晚大伙先打。今天我要007了，来个好点的高等模块水晶爽一爽。”群主仍然同平常一样，笑着对他说，“龙欣，你盟战又0分过图了！”但他这回却不十分分辩，单说了一句“不要取笑！”“取笑？要是好好打盟战，怎么会被安排去之慎？”龙欣低声说道，“蹭，蹭奖励……”他的眼色，很像恳求群主，不要再提。此时已经聚集了几个人，便和群主都笑了。我替他买了一个高等模块水晶，又**飞机场刷新了三次**[^刷飞机]，刚好花完。他从机器人列表中选中一个二星探长，喂给了锻造20级的5星声波（原来他便用准备这样的资源完成他声波头像的夙愿）。不一会，他退出了锻造界面，在之慎一排“10天前”登录的账号之上，被念总升为了之慎的盟主。

[^刷飞机]: 10钻一次的飞机场刷新，一般被认为是极为土豪的行为。
[^官对]: 龙欣在争执不过的时候就简单地用“x对”（x表示跟他吵的那位）这么遮乎过去。
[^4.7]: “4.7寸以上的手机都是垃圾”；“不是，我觉得4寸的手机最大，4寸屏（包以上）太大，不好放”；“最想用的是诺5320（小5），可惜过时了”

自此以后，又长久没有看见龙欣。到了年关，群主翻开聊天记录，“龙欣还没辞工回家呢！”到第二年的端午，又说“龙欣还没辞工回家呢！”到中秋可是没有说，再到年关也没有看见他。

我到现在终于没有见——大约龙欣的确辞工弃坑了。 

# 中篇

2020年的10月8日，卡邦把论坛关了，只剩下要翻墙才能上的Discord聊天频道；除了访问外网比较方便的震天威[^震天威]，其他人都不再操心游戏的新闻。**陈老或**[^陈大彧]忽然坐起身，擦着火柴，点上遍身油腻的灯盏，茶馆的两间屋子里，便弥满了青白的光。

[^震天威]: 指玩家“震天威M3GATR0N”。老骥伏枥，志在千里，年近花甲的他在基本上毕业一个号后，毅然决然再从零开始练第二个！

“之光盟主，你就去么？”是一个老玩家**全村的寡妇**[^全村的寡妇]的声音。里边的小屋子里，也发出一阵咳嗽。

[^陈大彧]: 指玩家“北京哪家呢”：龙欣的人生导师。名字中的“彧”字是生僻字，往往被认为是“或”字。所以一般认为龙欣说“今晚大伙先打”其实就是想说“今晚**大或**先打”。
[^全村的寡妇]: 指玩家“JACK_PRIME”，小钢索的欢喜冤家。黑带九段杠精、胶佬、盟战划水专业户（“让全球70亿观众久等啦！”的始作俑者）

“唔。”老或一面听，一面应，一面扣上衣服；伸手过去说，“你给我罢。”

寡妇在水晶里面翻了半天，翻出一个绝版的破碎的土地水晶，交给老或，老或接了，抖抖的打开开水晶界面，往那个洞里面塞进去，又拉出来，反复几次，直到一哆嗦，便感索然无味，点上灯笼，吹熄灯盏，走向里屋子去了。那水晶转到窸窸窣窣地停止，得到25个T1B精华，接着便是一通咳嗽。老或候他平静下去，才低低的叫道，“龙欣……你不要起来。……盟战么？盟友会代打的。”

老或听得龙欣不再说话，料他安心睡了；便出了门，走到街上。街上黑沉沉的一无所有，只有一条灰白的路，看得分明。灯光照着他的两脚，一前一后的走。有时也遇到几只狗，可是一只也没有叫。天气比屋子里冷多了；老或倒觉爽快，仿佛一旦变了少年，得了神通，有给人生命的本领似的，跨步格外高远。而且路也愈走愈分明，天也愈走愈亮了。

老或正在专心走路，忽然吃了一惊，远远里看见一条丁字裤，差点亮瞎了眼，原来是**飞飞**[^飞飞]正在秀自己的新女友。他便退了几步，寻到一家关着门的铺子，蹩进檐下，靠门立住了。好一会，身上觉得有些发冷。

[^飞飞]: 指玩家“cyz飞飞”，知名胶佬，知名PUA，深得龙欣仰慕。

“哼，又是已婚的。”

“你不要，给我啊……。”

老或又吃一惊，睁眼看时，几个人从他面前过去了。一个还回头看他，样子不甚分明，但很像盟战缺人的盟主见了野生高战力账号出现在公屏一般，眼里闪出一种攫取的光。老或看看灯笼的**塞伯坦之光**，已经熄了。仰起头两面一望，只见许多古怪的人，三三两两，鬼似的在那里徘徊；定睛再看，却也看不出什么别的奇怪。

没有多久，又见几个群友，在那边聊天；衣服前后的一个大白圆圈里写着“野生群管”，远地里也看得清楚，他们经过之后，一下涌来好些人，合作一堆，潮一般向前进；突然立住，簇成一个半圆。

老或也向那边看，却只见一堆人的后背；颈项都伸得很长，仿佛许多鸭，被无形的手捏住了的，向上提着。静了一会，突然一声娇喘——飞飞从女友丁字裤中抽出了一张什么东西，大家“噫”地叫了起来，轰的一声，都向后退；一直散到老或立着的地方，几乎将他挤倒了。

“喂！一手交能量块，一手交货！”一个身上写着“墨家”二字的大汉[^墨家]，站在老或面前，眼光正像两把刀，刺得老或缩小了一半。那人一只大手，向他摊着；一只手拿着一张“盟战划水证”，还一点一点的往下滴着不可描述的液体。

[^墨家]: 墨家机关城，龙欣从之慎出走后新的划水盟。


老或慌忙摸出2000能量块，抖抖的想交给他，却又不敢去接他的东西。那人便焦急起来，嚷道，“怕什么？怎的不拿！”老或还踌躇着；墨家大汉便抢过灯笼，一把扯下纸罩，裹了划水证，塞与老或；一手抓过能量块，转身去了。嘴里哼着说，“这老东西……。”

“这给谁用的呀？”老或也似乎听得有人问他，但他并不答应；他的精神，现在只在这张证明上，仿佛抱着一个十世单传的婴儿，别的事情，都已置之度外了。他现在要将这张证明，交给家里那失去盟战能力但又不肯放弃的龙欣，收获许多幸福。太阳也出来了；在他面前，显出一条大道，直到他家中，后面也照见街头破匾上“雷霆拯救隊[^雷霆]”这五个黯淡的金字。 

[^雷霆]: 雷霆拯救隊——权健盟的新形态，汇聚了多位佣军高手，却始终功亏一篑。直到得到了龙欣的精神力注入，才得以完成难度100的盟战探索。


# 下篇
给龙欣的这篇传记，前前后后写了已经不止一年了。但一面要写，一面又往回去改，因为他的轶事实在太多，私聊我希望在文中登场的朋友也不少，这足见我不是一个“严谨”的人，因为从来不朽之笔，是要早早写下，交与人以文传，文以人传的——好在究竟谁靠谁传，似乎渐渐的不重要了起来，毕竟在传龙欣的趣事方面，大家都仿佛思想里极有默契似的。

龙欣不独是姓名籍贯有些渺茫，连他先前的“行状”也渺茫。因为塞伯坦联盟的人们，大都只拿他玩笑，从来没有留心他的“老家”的。而龙欣自己也不说，独有在艳羡别人有美国绿卡的时候，间或瞪着眼睛道：

“我，我是汉民[^汉民]——比你的根要纯正多啦！你算是什么东西！”

[^汉民]: “这群人均大佬**士**豪（注意不是土豪），除了我”；“能移民还穷？能去外国的一般都有钱”

龙欣没有固定的盟，号交给雷霆的人代打；自己也没有固定的职业，只给人家做短工，建筑工地、小本文秘，不一而足。有时一个同盟打盟战的周期较长，他也或自己给上号打打药，但一到盟战开始就走了。所以，人们盟战忙碌的时候，也还记起龙欣来，然而记起的是划水，并不是“老家”；一闲空，连龙欣都早忘却，更不必说“老家”了。只是有一回，有一个老头子颂扬说：“龙欣历史学得真好！”这时龙欣赤著膊，懒洋洋的瘦伶仃的正在他面前，别人也摸不著这话是真心还是讥笑，然而龙欣很喜欢。

龙欣又很自尊，所有百炼为战的玩家，全不在他眼神里，甚而至于对于之刃、之光的盟主也有以为不值一笑的神情。加之收藏了几个公知出没的在线论坛，龙欣自然更自负，然而他又很鄙薄公知，譬如百炼为战里面侦查系控场能力极强的汽车人情报官，盟友都叫“警车”，公知也叫“警车”，龙欣却叫“白条”，他想：这是错的，可笑！公知们早晚要见到真的警车！


龙欣“苗儿正”，根儿红，而且“历史好”，本来几乎是一个“完人”了，但可惜他习惯上还有一些缺点。最恼人的是他的微信头像，颇有一种不知为何的模糊和反动[^头像]。开始的时候大家只是说“龙总又换头像了”，后来推而广之，直接说“换了”。于是只要有人一犯讳，不问有心与无心，龙欣便发起怒来，估量了对手，群里话多的他便争辩，不太出来冒泡的他便大骂，然而不知怎么一回事，总还是龙欣吃亏的时候多。于是他渐渐的变换了方针，大抵改为骂完马上撤回。

[^头像]: 龙欣曾经换过一个人挥舞着国民党旗的头像。


谁知道龙欣采用撤回主义之后，塞盟闲人们便愈喜欢玩笑他。一见他冒泡，他们便假作吃惊的说：

“哟，龙总亲自打字啊。”

龙欣照例的发了句“少来”便立即撤回。

“撤回干什么，怀了孕一起想办法啊！”

“就他还有怀孕的烦恼？”

“哈哈哈哈……”

龙欣没有法，只得另外想出报复的话来：

“你丫杠精啊？……”


这回惹来了真正的杠精[^神球]。龙欣在形式上打败了，被杠精揪住话茬儿，在群里引用回复了四五次，这才心满意足的得胜的走了，龙欣站了一刻，心里想，“我总算被儿子引用，现在的世界真不像样……”于是也心满意足的得胜的走了。

龙欣想在心里的，后来每每说出口来，所以凡是和龙欣玩笑的人们，几乎全知道他有这一种精神上的胜利法，此后每逢挤兑他的时候，人就先一著对他说：

“龙欣，这不是儿子杠老子，是骂畜生，畜生懂么！”

龙欣连连说道：

“你对，你对好不好？别拆台，还不行么？”

但虽然是这样，替他带号的兄弟也并不放，仍旧在把他空空的存储室截了图发到五六个群，这才心满意足的得胜的走了，他以为龙欣这回可遭了瘟。然而不到十秒钟，龙欣也心满意足的得胜的走了，他觉得他是第一个能够自轻自贱的人，除了“自轻自贱”不算外，馀下的就是“第一个”。状元不也是“第一个”么？“你算是什么东西”呢！？

龙欣以如是等等妙法在网络上克服怨敌之后，便愉快的在生活中跑到酒店里喝几碗酒，又和别人调笑一通，口角一通，又得了胜，愉快的回到雷霆拯救队，踢掉正在给自己打特殊的账号，开了一个高等模块水晶，放倒头睡着了。假使有网贷额度，他便去贷款，然后在工友前显摆，声音他最响：

“龙欣借你四百！”

“咳～～龙哥哥威武～～啦！”工友乐滋滋把钱收着。“龙欣的钱钱拿过来～～！”

“借借借，老子有得是钱！”

龙欣的钱便在这样的歌吟之下，渐渐的输入别个汗流满面的人物的腰间。他终于发现本金加利息要还1.3万，只好跑到各个群里发牢骚，让别人着急，替他想了各种点子催工友还钱，然后恋恋的回到家，第二天，跟没事人似的继续混着。


一日，龙欣在群里无可适从的盯着聊天。

突然蹦出来一张开箱图，他的对头又到了。这也是龙欣最厌恶的一个人。他先前跑上城里去进洋学堂，不知怎么又跑到澳洲去了，半年之后疫情原因他回到家里来，胡子也没了，喉结也不见了，他的母亲大哭了十几场。后来，他的母亲到处说，“这孩子是是被坏人灌醉了酒，把蛋给摘了。本来可以找到老婆，现在只好等长出来再说了。平常多给他买买玩具，分散一下他的注意力。”然而龙欣不肯信，偏称他“假太监”，一见他晒图，一定在肚子里暗暗的咒骂。

龙欣尤其“深恶而痛绝之”的，是他从来不买变4的红刺。FT飞天虎也买？就是没有了做人的资格；弹簧买四个，必然是倒爷。

这“假太监”近来了。

“小肛——缩……”龙欣历来本只在肚子里骂，没有出过声，这回因为正气忿，因为要报仇，便不由的轻轻的打字发到了群里。

本想马上撤回，不料这太监却学会了截图——转手发群里——抓着龙欣就骂。龙欣在这刹那，便知道大约要杠他了，赶紧发个“肛大爷我错了”，耸了肩膀等候着，果然，啪的一声，似乎确凿杠在自己头上了。

“小孩拿我手机乱发的！”龙欣分辩说。

“啪！啪！FT弹簧780原价转单，快转账过来！”

在龙欣的记忆上，这大约要算是生平第二件的屈辱。幸而出了780大洋买下一个没什么用的玩具后，于他倒似乎完结了一件事，反而觉得轻松些，而且“忘却”这一件祖传的宝贝也发生了效力，他慢慢的走，将到下一轮盟战开始时，想到又有人给代打，早已有些高兴了。

但对面走来了新入坑的热和无战[^热和无战]。龙欣便在平时，看见他也一定要唾骂，而况在屈辱之后呢？他于是发生了回忆，又发生了敌忾了。

[^热和无战]: 指玩家“中国热爱和平 世界永无战争”，被之夜老王称为“和平少年”的纯洁初中生，加入之夜后一直因为之夜开车速度太快而感到苦恼。

“我不知道我今天为什么这样晦气，原来就因为见了你！”他想。

他迎上去，大声的吐一口唾沫：

“咳，呸！”

热和无战全不睬，低了头只是走。龙欣搜索了一下他的ID，突然截图把他最强战力的机器人发群里，呆笑着，说：

“萌新！快去锻造，老王[^老王]等着你……”

[^老王]: 指玩家“ufo78a”。塞伯坦之夜盟主，擅长思想工作，诚心为盟友服务。

“你怎么乱截图……”热和无战满脸通红的说，一面赶快锻造。

群里的人大笑了。龙欣看见自己的勋业得了赏识，便愈加兴高采烈起来：

“陈老或能截图[^截图]，我不能截？”

[^截图]: 陈大彧的一项绝活就是对服务器上所有高战力的玩家了如指掌。通过保存截图，他忠实地记录着国盟和外盟的大神的发展进度，也始终像灯塔一样告诫着所有玩家：“毕业？你还差得远。”

群里的人大笑了。龙欣更得意，而且为了满足那些赏鉴家起见，再又把他总机器人数和防御战力单独放大了截图发群里，才放手。

他这一战，早忘却了飞飞，也忘却了假太监，似乎对于今天的一切“晦气”都报了仇；而且奇怪，又仿佛全身比拍拍的响了之后轻松，飘飘然的似乎要飞去了。

“这断子绝孙的龙欣！”远远地听得热和无战的带哭的声音。

“哈哈哈！”龙欣十分得意的笑。

“哈哈哈！”群里的人也九分得意的笑。



有人说：有些胜利者，愿意敌手如虎，如鹰，他才感得胜利的欢喜；假使如羊，如小鸡，他便反觉得胜利的无聊。又有些胜利者，当克服一切之后，看见死的死了，降的降了，"臣诚惶诚恐死罪死罪"，他于是没有了敌人，没有了对手，没有了朋友，只有自己在上，一个，孤另另，凄凉，寂寞，便反而感到了胜利的悲哀。然而龙欣却没有这样乏，他是永远失意永远愤青的：永远认为现在的民生、政治是要比古代、比GMD治下还不如，遑论和欧美体系相比[^政体]。只要还能找到一点不足之处，他是一定会出来发发牢骚的。然而因总害怕群友喷他，于是一般牢骚话发出，不出两分钟，立马撤回，留下一串“龙欣撤回了一条消息”和勾引出来各种“撤回有用吗，插进去再抽出来等于没插吗？”的表情包。后来还喜欢加上个“闪人”，不给他人反击的空间。

[^政体]: “马资都不好，唯有古中汉文明好。”

看哪，他飘飘然的似乎要飞去了！

然而这一次的胜利，却又使他有些异样。他飘飘然的飞了大半天，飘进塞伯坦之刃群，照例应该躺下便打鼾。谁知道在这群中，他感到责任重大，他觉得自己的大名有点古怪：仿佛比平常庄严些。不知道是盟主安排了重要的任务在他身上，还是他在大群中被雨巷[^雨巷]、神球和Sunny[^Sunny]教训得疲软了？……

[^雨巷]: 指玩家“000811”，塞伯坦联盟早期玩家。
[^Sunny]: 指玩家“i.Sunny”，塞伯坦之缘盟主，海外进步爱国人士。
[^神球]: 指玩家“无敌鲨鱼精”，号称人形ETC的杠神，在某次混战中被龙欣误以为是五毛党小粉红。


"断子绝孙的龙欣！"



"女人，女人！……"他想。

"……和尚[^和尚]动得……女人，女人！……女人！"他又想。

[^和尚]: 指三疯和尚，擅泡妞，经常教育龙欣要热爱生活。



这一天，龙欣在某微信好友处觅得一段猛片，吃过晚饭，便掏出4.7寸的iPhone看片，1分钟后进入了梦乡。

胖迪，是龙欣心中的女神，居然有流出的大尺度视频？女神一样翩翩而来，在长凳上坐下了，而且和龙欣闲天：

"可青[^可青]两天没上你号哩，因为库存里没有药……"

[^可青]: 指玩家“有可青”，原之刃盟友，后入雷霆拯救队。为龙欣专职盟战带打。



"女人……热巴……这小贱货……"龙欣想。

"雷霆拯救队看样子打不了几场全探索了……"

"女人……"龙欣想。

龙欣放下手机，站了起来。

"我们的心跳盟主[^心跳盟主]……"胖迪还唠叨说。

[^心跳盟主]: 指玩家“心跳权健”。原qj168盟主，解散后成立了雷霆拯救队，专门搜罗雇佣兵打盟战。

"我和你困觉，我和你困觉！"龙欣忽然抢上去，对她跪下了。

一刹时中很寂然。

"阿呀！"龙欣突然两腿一抖，顿觉一切皆索然无味，便进入了梦乡。


# 尾声
由于经营不善，百炼为战在印度公司手上也没有活过两年，终于在五星6阶发布后因为bug太多而无疾而终。玩家们四散而去，有的成了公司领导，有的成了玩具大咖，或者各自岗位上的佼佼者，有的顺利抱得美人归。但他们都有一个共同的特点：对百炼为战的生涯绝口不提。

一日是天气很冷的午后，我来陈老或家吃过午饭，坐着喝茶，觉得外面有人进来了，便回头去看。我看时，不由的非常出惊，慌忙站起身，迎着走去。

这来的便是龙欣。虽然我一见便知道是龙欣，但又不是我这记忆上的龙欣了。他身材增加了一倍；先前的紫色的圆脸，已经变作灰黄，而且加上了很深的皱纹；眼睛也像他父亲一样，周围都肿得通红，这我知道，在工地翻沙子的人，终日吸着粉尘，大抵是这样的。他头上是一顶破毡帽，身上只一件极薄的棉衣，浑身瑟索着；手里提着一个纸包和一支长烟管，那手也不是我所记得的一不小心把侦查T4C点给反冲升5阶的手，却又粗又笨而且开裂，像是松树皮了。

我这时很兴奋，但不知道怎么说才好，只是说：

“阿！龙欣哥，——你来了？……”

我接着便有许多话，想要连珠一般涌出：红刺、中汉、马红、开车、渣男，……但又总觉得被什么挡着似的，单在脑里面回旋，吐不出口外去。

他站住了，脸上现出欢喜和凄凉的神情；动着嘴唇，却没有作声。他的态度终于恭敬起来了，分明的叫道：

“公理天城翻译官老爷！……”

我似乎打了一个寒噤；我就知道，我们之间已经**隔了一层可悲的厚障壁**了。我也说不出话。

他回过头去说，“龙欠，给老爷磕头。”便拖出躲在背后的孩子来，这分明正是一个二十年前的龙欣，只是黄瘦些，颈子上没有银圈罢了。“这是我小孩，三岁，正常孕，没有见过世面，躲躲闪闪……”

陈老或和寡妇下楼来了，他们大约也听到了声音。

“听说百炼关服了，我实在难过得不得了，知道老爷回来……”龙欣说。

“阿，你怎的这样客气起来。你们先前不是哥弟称呼么？还是照旧：翻哥儿。”老或高兴的说。

“阿呀，干爹真是……这成什么规矩。那时是孩子，不懂事……”龙欣说着，又叫龙欠上来打拱，那孩子却害羞，紧紧的只贴在他背后。

“他就是龙欠？不是代孕的？都是生人，怕生也难怪的；还是寡妇和他去走走。”老或说。

寡妇听得这话，便来招龙欠，龙欠却松松爽爽同他一路出去了。老或叫龙欣坐，他迟疑了一回，终于就了坐，将长烟管靠在桌旁，递过纸包来，说：

“那1.3万的网贷到现在还没还清，一直**欠**着，孩子生出来也缺**斤**少两的，于是小孩直接起名‘龙欠’也是合适的吧。毕竟人再穷，文化气息是不能少的……”

我问问他的景况。他只是摇头。

“非常难。第6个游戏账号也托人代打了，却总是带不动……又没法氪金……什么地方都要钱，没有……工资又少。你们广州，黑人这个问题很严重，长此下去，要亡国啊……”

他只是摇头；脸上虽然刻着许多皱纹，却全然不动，仿佛石像一般。他大约只是觉得苦，却又形容不出，沉默了片时，便拿起手机打开微信，发了几条消息。等我去看时——

>*“龙欣”撤回了一条消息*

>*“龙欣”撤回了一条消息*

>*“龙欣”撤回了一条消息*

**（全文完）**